name: lint

# developブランチにpush時にlintをかける
on: [push]

# lintをかける
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn lint
      - run: yarn prettier
      - run: yarn stylelint:fix
