name: storybook_deploy

# 一時的にデプロイ状況を見るためにpush時にデプロイが走るように変更
# on:
#   push:
#     branches:
#       - develop

on: push

jobs:
  deploy:
    name: deploy_for_Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          storybookBuildDir: public
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
