name: storybook_deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: storybook_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        uses: yarn install
      - name: build storybook
        run: yarn build-storybook
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
